### PR TITLE
Remove rustc dependecy, get TARGET and HOST from build script instead

### PR DESCRIPTION
**Pull request by malbarbo**
Fixes https://github.com/laumann/compiletest-rs/issues/91

### CODE REVIEW

**Comment by malbarbo** [comment]
It would be great if a new release could be made.

**Comment by laumann** [comment]
Looks good, but could it be made a feature instead of a hard removal? Something like `norustc` (so it's enabled by default).

**Comment by laumann** [comment]
#106 was merged which added this as `norustc` feature.

**Comment by laumann** [comment]
@malbarbo [0.3.8](https://crates.io/crates/compiletest_rs/0.3.8) is out

**Comment by malbarbo** [comment]
Thanks for moving this forward!

**Comment by laumann** [comment]
@malbarbo Don't thank me, thank @messense :-) Let me know if works for you.

**Pull request closed without merging**
