### PR TITLE
Use "log" crate, remove a couple feature flags

### PR DESCRIPTION
**Pull request by erickt**
One small step on the path to stable Rust...

### CODE REVIEW

**Comment by laumann** [comment]
Thanks!

Apart from the using the log crate, I think you can have these changes merged into rustc's compiletest as well.

**Comment by Manishearth** [comment]
They won't be, since rustc can't depend on cargo crates.

So there's a lot of growing interest in compiletest (including https://internals.rust-lang.org/t/proposing-compiletest-for-the-nursery/2681), so perhaps we should allow it to deviate from rustc, and maintain it as a separate lib. What do you think?

**Comment by laumann** [comment]
@Manishearth Yes, but I think 272ad53 could be merged into rustc

I think we should just merge this...

**Comment by Manishearth** [comment]
Sure, sounds good to me!

**Pull request merged**
