### PR TITLE
 Replace tempdir by tempfile and bump version

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by laumann** [comment]
Hi @Eijebong, thanks for your PR! What is the reasoning behind this change? Is tempdir deprecated or something?

**Comment by laumann** [comment]
Ooops, I should learn to read commit messages, sorry :-)

**Comment by Eijebong** [comment]
:D No problem

**Comment by laumann** [comment]
LGTM, and test-project runs just fine, thank you!

**Comment by laumann** [comment]
[0.3.9](https://crates.io/crates/compiletest_rs/0.3.9) is out :tada:

**Pull request merged**
