### PR TITLE
Add basic `bless` support

### PR DESCRIPTION
**Pull request by phansch**
This adds basic `bless` support. Unfortunately without support for `miri` because I wasn't able to untangle it properly so far.

Should be merged after #232

### CODE REVIEW

**Comment by phansch** [comment]
So, the second commit adds a new testsuite as well. I think it's an improvement over the current one because it allows to quickly add new tests for different compiletest configurations. In this case for the `bless` config.
If we wanted to test `bless` support the old way, we would have to create a second `test-project`. The same for any other configuration.

It's a simplified version of [`cargo-test-support`](https://github.com/rust-lang/cargo/tree/master/crates/cargo-test-support). If we ever unify both compiletest variants, it should be possible to keep that testsuite to avoid unexpected bugs.

**Comment by phansch** [comment]
triggering a new build

**Review by Manishearth — APPROVED** [review]

**Comment by phansch** [comment]
Looks like the GitHub API is having a bad day:

> Warning: Failed to download action 'api.github.com/repos/actions/checkout/zipball/5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f'. Error: Response status code does not indicate success: 500 (Internal Server Error).

**Comment by Munksgaard** [comment]
Not quite sure what's going on [here](https://github.com/laumann/compiletest-rs/pull/231/checks?check_run_id=1864951482#step:5:81). Any guess @phansch ?

**Comment by Manishearth** [comment]
The nightly build is failing

```
error[E0560]: struct `TestOpts` has no field named `filter`
   --> src/lib.rs:114:9
    |
114 |         filter: config.filter.clone(),
    |         ^^^^^^ help: a field with a similar name exists: `filters`

```

**Comment by phansch** [comment]
Odd, I can't reproduce the error above locally, let's see if a rebase fixes it.

**Comment by phansch** [comment]
This is due to https://github.com/rust-lang/rust/pull/81356, I'll try and see if I can get it upstreamed into the `tester` crate later today. Otherwise, we'll need to use `filters` only if the `rustc` feature is enabled.

**Comment by phansch** [comment]
@Munksgaard Thank you for the quick merge! Do you think it would be possible to release a 0.6 version as well?

**Comment by Munksgaard** [comment]
Yes, I'll do that when the CI for #225 passes :)

**Comment by Munksgaard** [comment]
Done!

**Pull request merged**
