### PR TITLE
Rustup https://github.com/rust-lang/rust/pull/58689

### PR DESCRIPTION
**Pull request by mati865**
Fix for the next (not yet released) nightly.

Fixes https://github.com/laumann/compiletest-rs/issues/159

### CODE REVIEW

**Comment by ljedrz** [comment]
I think https://github.com/laumann/compiletest-rs/issues/159 needs to be fixed first for this to work :/.

**Comment by mati865** [comment]
Let's make the CI green.

**Comment by mati865** [comment]
Should I add `cfg` checking for `stable` feature to this field?

**Comment by laumann** [comment]
Hi @mati865, thanks for opening this PR!

> Should I add `cfg` checking for `stable` feature to this field?

Yeah, that looks to be necessary.

**Comment by mati865** [comment]
All green.

**Comment by Xanewok** [comment]
If merged, please do a point release (so that we can fix Clippy and RLS without some of the branch acrobatics required across multiple repositories), thanks!

**Comment by laumann** [comment]
> All green.

Awesome, thanks!

> If merged, please do a point release (so that we can fix Clippy and RLS without some of the branch acrobatics required across multiple repositories), thanks!

Will do.

**Comment by laumann** [comment]
@Xanewok @mati865 Just for me to get the timeline right: When this PR was created, the nightly this fix is inteded for wasn't released yet, but it now, right?

**Comment by mati865** [comment]
> @Xanewok @mati865 Just for me to get the timeline right: When this PR was created, the nightly this fix is inteded for wasn't released yet, but it now, right?

Exactly.

**Comment by laumann** [comment]
@Xanewok @mati865 Version [0.3.19](https://crates.io/crates/compiletest_rs/0.3.19) is out!

**Comment by Xanewok** [comment]
Thank you!

**Pull request merged**
