### PR TITLE
improvements suggested by clippy

### PR DESCRIPTION
**Pull request by llogiq**
I changed a lot of `.to_string()` that can be better written as `.to_owned()`, and removed some redundant closures.

I also note that there is quite a bit of shadowing; however there are some false positives (because I've yet to support more destructuring patterns), so I've disabled that lint for now.

### CODE REVIEW

**Comment by Manishearth** [comment]
I'm not sure if we should merge this, compiletest-rs is based on (ported from) the in-tree compiletest from rustc, so we should keep those as similar as possible.

Though you could start refactoring stuff in rustc itself :)

**Comment by llogiq** [comment]
In that case, I will try to apply my changes to rustc first. I'm closing this for now. I can reopen once rustc has the changes.

**Comment by llogiq** [comment]
I have crafted a [PR](https://github.com/rust-lang/rust/pull/28152) to rust-lang/rust.

**Comment by Munksgaard** [comment]
:+1:

**Comment by llogiq** [comment]
My Rust PR was merged. So the changes should be pretty much the same (the Rust version has one more file that we don't have here, though). Feel free to either merge from here or from the Rust sources.

**Comment by laumann** [comment]
@llogiq Maybe we should consider updating compiletest to reflect the latest version in the rust compiler...

@Manishearth Will you release a new version?

**Pull request merged**
