### PR TITLE
Update to 1.9.0-nightly (74b886ab1 2016-03-13)

### PR DESCRIPTION
**Pull request by mcarton**
I copied back everything, so maybe too much? The broken stuff was just in `src/procsrv.rs` with `std::dynamic_lib` having been removed.

See https://travis-ci.org/Manishearth/rust-clippy/builds/115863948 for the error it caused.

### CODE REVIEW

**Comment by Manishearth** [comment]
Does this break clippy?

Perhaps we should add a travis test that clones clippy, uses a path override to this compiletest, and runs the tests.

(A submodule might not work since cargo clones through submodules, which leads to double clippy being downloaded)

**Comment by mcarton** [comment]
Clippy currently cannot be tested on the last nightly. With that PR, it needs the following patch:
```rust
diff --git a/tests/dogfood.rs b/tests/dogfood.rs
index 61e37c2..b5ae813 100644
--- a/tests/dogfood.rs
+++ b/tests/dogfood.rs
@@ -1,7 +1,11 @@
+#![feature(test)]
+
 extern crate compiletest_rs as compiletest;
+extern crate test;
 
-use std::path::Path;
 use std::env::var;
+use std::path::PathBuf;
+use test::TestPaths;
 
 #[test]
 fn dogfood() {
@@ -20,5 +24,10 @@ fn dogfood() {
 
     config.mode = cfg_mode;
 
-    compiletest::runtest::run(config, &Path::new("src/lib.rs"));
+    let paths = TestPaths {
+        base: PathBuf::new(),
+        file: PathBuf::from("src/lib.rs"),
+        relative_dir: PathBuf::new(),
+    };
+    compiletest::runtest::run(config, &paths);
 }
```

I did not realize this would break the API, is this a problem? If so, I can just revert everything and just fix the `std::dynamic_lib` stuff (but Rust’s `compiletest` [has been changed a lot recently](https://github.com/rust-lang/rust/commits/master/src/compiletest))

**Comment by Manishearth** [comment]
Should be a major version bump, then?

**Comment by Manishearth** [comment]
I'm fine with landing this first, fixing up clippy, and later landing CI.

**Comment by mcarton** [comment]
The example script on the README should not be broken by the way (Clippy’s own `tests/compile-test.rs` needs no change).

**Comment by Manishearth** [comment]
published as 0.1.0

**Comment by Manishearth** [comment]
Doesn't seem to be enough to rustup, we're getting trouble with overlapping dependencies

https://travis-ci.org/Manishearth/rust-clippy/builds/116076516

**Comment by mcarton** [comment]
Looks like `regex-syntax` *0.3* has been published, something wants to use that but our `regex-syntax` dep is *0.2.2*. Try updating it to *0.3.0* in *Cargo.toml* maybe?

**Comment by Manishearth** [comment]
Yeah. Part of the problem is that unlike cargo compiletest doesn't know how to select deps with extern flags. I'll have a look at the deptree later.

**Pull request merged**
