### PR TITLE
Bump tester crate version to 0.5.0

### PR DESCRIPTION
**Pull request by messense**

### CODE REVIEW

**Comment by messense** [comment]
Yanked 0.4.2 and bumped version to 0.5.0.

**Comment by laumann** [comment]
Thanks @messense, I'd like to have #142 merged before merging this, is that OK?

**Comment by messense** [comment]
Sure.

**Comment by laumann** [comment]
@messense OK, #142 is merged, could you rebase this on `master`?

**Comment by messense** [comment]
Travis passed.

**Comment by laumann** [comment]
Excellent!

**Pull request merged**
