### PR TITLE
Changed deprecated String::from_str to String::from

### PR DESCRIPTION
**Pull request by llogiq**
This is breaking our rust-clippy build on current nightly.

It's just a one liner to make review easy :smile:

### CODE REVIEW

**Comment by laumann** [comment]
Thank you

**Comment by llogiq** [comment]
You're very welcome. 

Are you going to release a new version on crates.io? The current 0.0.4 appears to be breaking builds.

**Comment by laumann** [comment]
Just did :smile:

**Comment by llogiq** [comment]
Thank you! :+1:

**Comment by laumann** [comment]
np

**Pull request merged**
