### PR TITLE
update for TestPaths being moved

### PR DESCRIPTION
**Pull request by dwrensha**
Fixes breakage from https://github.com/rust-lang/rust/pull/47106.

### CODE REVIEW

**Comment by laumann** [comment]
Thanks! LGTM.

**Comment by laumann** [comment]
@dwrensha Does this warrant a 0.3.5?

**Comment by SergioBenitez** [comment]
@laumann Yes, we'll need a 0.3.5.

On a broader note: we should really look into having `compiletest` be more independent from `rustc` so that it doesn't break on upstream changes. Has anyone looked into this, and if so, how much effort would it involve?

**Comment by laumann** [comment]
[0.3.5](https://crates.io/crates/compiletest_rs/0.3.5) is out.

@SergioBenitez I honestly haven't looked into reducing (or eliminating) the rustc dependency - this project has only been focused on extracting the compiletest "as is" (as much as possible) from rustc. I suspect that a more substantial rewrite should not be too difficult, but for the users that I know of the current approach seems to be not too bad. So I'm somewhat in the camp of "if it ain't broke, don't fix it". That said, my impression is that the code could benefit from a rewrite, for example to implement a builder pattern around `Config` and using Path/PathBuf for some variables that are currently modeled with String.

**Pull request merged**
