### PR TITLE
Add support for upstream's 'edition' flag

### PR DESCRIPTION
**Pull request by phansch**
Needs to be merged after https://github.com/laumann/compiletest-rs/pull/181

### CODE REVIEW

**Comment by Munksgaard** [comment]
Now that #183 has superseeded #181, could you perhaps rebase this PR so we can merge it?

**Comment by phansch** [comment]
@Munksgaard this needs https://github.com/laumann/compiletest-rs/pull/171 first, to make use of the nightly only testsuite for `async`.

**Comment by Munksgaard** [comment]
I've gone ahead and merged #171, so with a rebase perhaps we can merge this PR as well?

**Comment by phansch** [comment]
@Munksgaard yup, I will rebase later today, thanks for the reminder!

**Comment by Munksgaard** [comment]
> @Munksgaard yup, I will rebase later today, thanks for the reminder!

No worries, I only just merged your other PR :grin:

**Comment by phansch** [comment]
Rebased and added 41ec893 to move the added test to the `nightly` test suite.

**Comment by Munksgaard** [comment]
Thanks!

**Pull request merged**
