### PR TITLE
Update dependencies and bump version

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by laumann** [comment]
Hi! Thanks for your PR, but #104 handles much of what is handled here

**Comment by laumann** [comment]
If you update this to just the version bump, I'll publish the new version today.

**Comment by Eijebong** [comment]
Oh :D Sorry I never look at open PRs when I do version bump because I'm way too lazy... I'll close this then.

**Comment by laumann** [comment]
Haha, no problem :-)

**Pull request closed without merging**
