### PR TITLE
Add some unit tests (rustc copy)

### PR DESCRIPTION
**Pull request by phansch**
Same as https://github.com/rust-lang/rust/pull/56841

### CODE REVIEW

**Comment by laumann** [comment]
I take it we want this merged before #151?

**Comment by phansch** [comment]
It's independent of #151 so can be merged whenever =)

**Comment by phansch** [comment]
I added the unit test execution to CI but it looks like running the unit tests an stable causes:

```
error[E0308]: mismatched types
   --> src/util.rs:116:1
    |
116 | / fn test_get_arch_failure() {
117 | |     get_arch("abc");
118 | | }
    | |_^ expected struct `test::TestDescAndFn`, found reference
    |
    = note: expected type `test::TestDescAndFn`
               found type `&test::TestDescAndFn`
```

**Comment by phansch** [comment]
I'm not really sure how to fix it. I guess the `tester` crate needs an update?

**Comment by messense** [comment]
> Hmm, the tester crate might need an update.

Sure thing. The repository is here: https://github.com/messense/rustc-test if any of you guys want to update it.

**Comment by phansch** [comment]
Maybe not 100% related, but would it make sense to depend on https://github.com/rust-lang/libtest instead of the `tester` crate in the future?

**Comment by laumann** [comment]
> Maybe not 100% related, but would it make sense to depend on https://github.com/rust-lang/libtest instead of the `tester` crate in the future?

Hmm, libtest seems to be targeted at nightly only, the `tester` crate is specifically to add stable support. I could be wrong though.

I tried a couple of times to dig into the error with the `tester` crate, but never got to the bottom of it (mostly due to lack of time).

**Comment by phansch** [comment]
I won't have time to dig into this either, so I'm going ahead and close this PR. If someone want's to pick it up, feel free to take it =)

**Pull request closed without merging**
