### PR TITLE
Move to GitHub Actions

### LINKED ISSUE #227: Move to Github Actions
Now that Travis is [closing down](https://news.ycombinator.com/item?id=25338983), perhaps we should look at moving to Github actions for our CI needs?

### PR DESCRIPTION
**Pull request by phansch**
This gets rid of both the AppVeyor build and the TravisCI build. The Travis CI build stopped triggering  some time ago. Instead, we're now using GitHub Actions for both Windows and Linux builds.

Closes #227

### CODE REVIEW

**Comment by phansch** [comment]
I'm.. at a total loss why it doesn't trigger any GH Actions build? Is it because I'm only a contributor?

**Comment by Munksgaard** [comment]
Perhaps we need to enable it?

**Comment by Munksgaard** [comment]
@laumann can you make me admin, or go take a look at the actions tab in settings yourself?

**Comment by Munksgaard** [comment]
Thank you for this, by the way, @phansch

**Comment by phansch** [comment]
> Perhaps we need to enable it?

Yup, must be a permission/setting issue; It works on my fork: https://github.com/phansch/compiletest-rs/pull/1

**Comment by phansch** [comment]
Alright, code-wise this is ready now. What needs to be done on the repo settings side would be:

1. Enabling GitHub Actions somewhere
2. Removing Appveyor from the build check requirements
3. Adding all the GitHub Actions builds to the build requirements.
  This probably can only be done _after_ they have all executed here once
  Maybe it's enough to close and re-open the PR to trigger the builds after 1) is done. That wouldn't require any pushes from my side.

**Comment by Munksgaard** [comment]
Thank you @phansch, I'll see what I can do.

**Comment by Manishearth** [comment]
IIRC for enabling github actions you just need to merge in a change to the workflows folder

**Comment by Manishearth** [comment]
@laumann I think you manually need to disable appveyor, i don't have access

**Pull request merged**
