### PR TITLE
Fix the run_ignored issue while supporting both nightly and stable

### LINKED ISSUE #131: Does not compile on latest nightly
I am getting this error:
```
error[E0308]: mismatched types                                                                                                                                                                                     
   --> /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.3.14/src/lib.rs:101:22                                                                                                             
    |                                                                                                                                                                                                              
101 |         run_ignored: config.run_ignored,                                                                                                                                                                     
    |                      ^^^^^^^^^^^^^^^^^^ expected enum `test::RunIgnored`, found bool                                                                                                                         
    |                                                                                                                                                                                                              
    = note: expected type `test::RunIgnored`                                                                                                                                                                       
               found type `bool`                                                                                                                                                                                   
                                                                                                                                                                                                                   
error: aborting due to previous error                                                                                                                                                                              
                                                                                                                                                                                                                   
For more information about this error, try `rustc --explain E0308`.                                                                                                                                                
```

### LINKED ISSUE #133: Stable build is broken: Could not find `RunIgnored` in `test`
```console
$ cargo +stable build --features stable
   Compiling compiletest_rs v0.3.14
error[E0433]: failed to resolve. Could not find `RunIgnored` in `test`
   --> src/lib.rs:101:52
    |
101 |         run_ignored: if config.run_ignored { test::RunIgnored::Yes } else { test::RunIgnored::No },
    |                                                    ^^^^^^^^^^ Could not find `RunIgnored` in `test`

error[E0433]: failed to resolve. Could not find `RunIgnored` in `test`
   --> src/lib.rs:101:83
    |
101 |         run_ignored: if config.run_ignored { test::RunIgnored::Yes } else { test::RunIgnored::No },
    |                                                                                   ^^^^^^^^^^ Could not find `RunIgnored` in `test`
```

### PR DESCRIPTION
**Pull request by laumann**
Fixes #133
Fixes #131

### CODE REVIEW

**Comment by laumann** [comment]
@dtolnay Could you test this? I did `cargo build --features stable` locally, so I'm hopeful that it works.

**Comment by dtolnay** [comment]
The right fix would be to update the `tester` crate with whatever changes happened in nightly. @messense @SimonSapin 

For now this looks good except for some warnings: #137. Would it be easy to include #134 here so that it stays working?

**Comment by laumann** [comment]
You're right, updating the `tester` crate would be the correct fix.

Are the warnings a problem?

> Would it be easy to include #134 here so that it stays working?

I'd rather have that in a separate PR. Plus I'm not very good at writing Travis build files

**Comment by dtolnay** [comment]
I can help with the build file but you'll need to enable Travis builds first: #138.

**Pull request merged**
