### PR TITLE
Upgrade to nightly

### PR DESCRIPTION
**Pull request by laumann**

### CODE REVIEW

**Comment by laumann** [comment]
This compiletest is quite a bit behind rustc/compiletest. This mostly just copies the changes from rustc/compiletest here. It should probably be a minor version bump to 0.3.0, because `Config` is not backwards compatible.

**Comment by laumann** [comment]
From the log it appears that last time this project was updated from rustc was `63c77214c`, 

To answer your question @SergioBenitez: Yes, it includes UI tests.

git log 63c77214c..master  --oneline src/tools/compiletest
```
2bffa31 compiletest: Change Config comments to doc comments
7a8d38e Additional libc cleanup
91bfe3f capture `adb shell` stdout
02e95e5 remove needless clone
88bac1f remove procsrv module
6f21239 remove `extra_args` argument
04dee08 return `Command` from make_compile_args
90a87be make `compose_and_run_compiler` take `Command`
0a666f8 remove `working_dir` argument
e385bc5 let `compose_and_run` take a `Command`
6601ffc replace procsrv functions with `Command`
1b6c960 use field init shorthand EVERYWHERE
0374e6a rustc: Rearchitect lints to be emitted more eagerly
4e5333c Don't needlessly build rustdoc for compiletest.
5aa8cc8 Only set cwd for test process, not compiler
c35030a Try running all tests using cwd
f4e329f Make compiletest set cwd before running js tests
cb92ab9 Reduce the usage of features in compiletest and libtest
4582ecd compiletest: Support custom normalization rules.
18712e6 compiletest: Refactor: Move the `ignore-{}` logic into its own method.
4a92ae2 Auto merge of #42896 - llogiq:clippy_compiletest, r=alexcrichton
7be171d fix a stray semicolon
bea4e60 Rollup merge of #42219 - pwoolcoc:add-allow-fail-to-libtest, r=GuillaumeGomez
1715559 address tidy error & comment
3f1cb30 compiletest: show details if GDB failed to execute.
3d25238 fixed some clippy warnings in compiletest
60dd83e add `allow_fail` test attribute
16da303 Add target option for linker environment variables
447297c Make wasm32 buildbot test LLVM backend
5c3d0e6 Switch to the crates.io `getopts` crate
406eddf Add a no-system-llvm compilecheck header
3e6c83d compiletest: Force directive to be first complete word in header comment.
38ef856 Introduce 'run-pass' header to 'ui' tests in compiletest. Fix issue #36516.
1a1ea25 Added --color flag to compiletest.
9111d07 make ui test output patch compatible #41948
fb6f845 Auto merge of #41863 - malbarbo:update-android-builder, r=alexcrichton
d23a650 compiletest: force GDB to print values in the Rust format.
49f793a ci: Update android ndk and sdk
ecd7b48 Rollup merge of #41678 - GuillaumeGomez:rustdoc-test-warnings, r=alexcrichton
d5863e9 Add Options type in libtest and remove argument
46b342f simplify the MirPass traits and passes dramatically
f30ed77 Add option to display warnings in rustdoc
e326e86 Auto merge of #41588 - cengizIO:master, r=nikomatsakis
ad1461e Auto merge of #41575 - alexcrichton:android-qemu-server, r=TimNN
2971d49 Auto merge of #41508 - michaelwoerister:generic-path-remapping, r=alexcrichton
7bc2cbf travis: Parallelize tests on Android
837817c use diff crate for compile-fail test diagnostics #41474
39ffea3 Implement a file-path remapping feature in support of debuginfo and reproducible builds.
0d63f13 Haiku: add missing cases of using LIBRARY_PATH
```

**Comment by Marwes** [comment]
Might this update fix the errors gluon gets with compiletest now? https://travis-ci.org/gluon-lang/gluon/jobs/273796629#L1645

**Comment by laumann** [comment]
@Marwes I don't know - maybe we could test it out?

**Comment by laumann** [comment]
@Marwes I'm trying to run `cargo test` now - are there any other options I should add?

**Comment by Marwes** [comment]
You need the `nightly` and the `test` feature to run the compiletest

**Comment by laumann** [comment]
Thanks, I got this far to run `cargo +nightly test --features test`.

I added:
```
[replace]
"https://github.com/rust-lang/crates.io-index#compiletest_rs:0.2.10" = { path = "/home/t/rust/compiletest-rs" }
```
to gluon's Cargo.toml, and the path points to my local checkout of the `update-to-nightly` branch.

Tests all passed. `rustc +nightly -Vv` says:
```
rustc 1.22.0-nightly (744dd6c1d 2017-09-02)
binary: rustc
commit-hash: 744dd6c1d5db522d5d3b7f2bb82abde5dc41cbeb
commit-date: 2017-09-02
host: x86_64-unknown-linux-gnu
release: 1.22.0-nightly
LLVM version: 4.0
```
So far it all looks OK. I'll update my nightly, run it again and get back to you.

**Comment by Marwes** [comment]
Sure you actually ran the compiletest? It should be `cargo +nightly test --features "test nightly" --test compiletest` and there should be r tests ran https://github.com/gluon-lang/gluon/blob/master/tests/compiletest.rs

**Comment by laumann** [comment]
No, I don't think I ran it - the output doesn't show any compile-fail, etc... I'll try it again, thanks for the tip.

**Comment by laumann** [comment]
OK, now I got:

```
$ OUT_DIR=target/debug cargo +nightly test --features "test nightly" --test compiletest
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running target/debug/deps/compiletest-da34192ad22bfe8e

running 1 test

running 4 tests
test [compile-fail] compile-fail/get-reference.rs ... ok
test [compile-fail] compile-fail/getable-reference-str.rs ... ok
test [compile-fail] compile-fail/store-ref.rs ... ok
test [compile-fail] compile-fail/getable-reference.rs ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

test compile_test ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by Marwes** [comment]
Yup that is what it should look like. Guess this PR unbreaks it! Thanks for looking into this! :)

When do you think a release may happen?

**Comment by laumann** [comment]
I'd like it to happen ASAP - it'll be version 0.3.0 because changes in `Config` breaks backwards compatibility.

@SergioBenitez Should we just merge and release 0.3.0?

**Comment by SergioBenitez** [comment]
@laumann I'm for it.

**Comment by laumann** [comment]
Nice, thanks, on it...

**Comment by laumann** [comment]
Done, @Marwes `compiletest_rs` 0.3.0 is [live](https://crates.io/crates/compiletest_rs/0.3.0)!

**Comment by Marwes** [comment]
@laumann Awesome! Thanks!

**Pull request merged**
