### PR TITLE
Upstream merge

### LINKED ISSUE #86: "every suggestion should have at least one span"
On the most recent nightly, 1.23.0-nightly (63739ab7b 2017-11-21), my compile-fail tests started failing with this error. The issue is reproduced as well in the test-project test cases in this repo. Is there a fix we need to grab from upstream?

```
test [compile-fail] compile-fail/asm-gated.rs ... FAILED
test [compile-fail] compile-fail/mut-suggestion.rs ... FAILED
test [compile-fail] compile-fail/multiple-errors.rs ... FAILED
test [compile-fail] compile-fail/trait-bounds-cant-coerce.rs ... FAILED
test [compile-fail] compile-fail/vector-cast-weirdness.rs ... FAILED
test [compile-fail] compile-fail/where-for-self.rs ... FAILED

failures:

---- [compile-fail] compile-fail/asm-gated.rs stdout ----
	thread '[compile-fail] compile-fail/asm-gated.rs' panicked at 'every suggestion should have at least one span', /checkout/src/libcore/option.rs:874:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- [compile-fail] compile-fail/mut-suggestion.rs stdout ----
	thread '[compile-fail] compile-fail/mut-suggestion.rs' panicked at 'every suggestion should have at least one span', /checkout/src/libcore/option.rs:874:4

---- [compile-fail] compile-fail/multiple-errors.rs stdout ----
	thread '[compile-fail] compile-fail/multiple-errors.rs' panicked at 'every suggestion should have at least one span', /checkout/src/libcore/option.rs:874:4

---- [compile-fail] compile-fail/trait-bounds-cant-coerce.rs stdout ----
	thread '[compile-fail] compile-fail/trait-bounds-cant-coerce.rs' panicked at 'every suggestion should have at least one span', /checkout/src/libcore/option.rs:874:4

---- [compile-fail] compile-fail/vector-cast-weirdness.rs stdout ----
	thread '[compile-fail] compile-fail/vector-cast-weirdness.rs' panicked at 'every suggestion should have at least one span', /checkout/src/libcore/option.rs:874:4

---- [compile-fail] compile-fail/where-for-self.rs stdout ----
	thread '[compile-fail] compile-fail/where-for-self.rs' panicked at 'every suggestion should have at least one span', /checkout/src/libcore/option.rs:874:4
```

### PR DESCRIPTION
**Pull request by valff**
Fixes #86.

### CODE REVIEW

**Comment by laumann** [comment]
@valff Thanks! This just updates the source to the current rustc:master?

**Comment by valff** [comment]
@laumann Yes, just copied src files (except `main.rs`), and added few fixes to `src/common.rs` and `src/lib.rs`.

**Comment by laumann** [comment]
@valff Cool!

**Comment by laumann** [comment]
I guess I should upload a new version...

**Pull request merged**
